### ISSUE TITLE
SvelteKit Adapter License

### ISSUE THREAD

**Issue by H0R5E** [lukaskoeller/freedev#13]
Hi, I noticed that you are using a modified version of my SvelteKit adapter. I'm glad you're finding it useful.

If you wouldn't mind I'd be really grateful if you could include the copyright notification with the source code, please? This is just to comply with the MIT license.

Many thanks,

Mat

**Comment by lukaskoeller** [comment]
Hey! Sure, I added it to the respective package. I added James Bray too which was missing in yours, since you credited him in your README

**Comment by H0R5E** [comment]
Thanks! I'll get that updated right away!
